name: Get Flag

on:
  workflow_dispatch:

jobs:
  get-flag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for OIDC login
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC Federated Identity)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download Flag from Blob
        run: |
          az storage blob download \
            --account-name iamazurelab3d26800f7 \
            --container-name flag \
            --name flag.txt \
            --file ./flag.txt \
            --auth-mode login
          cat ./flag.txt
